/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddIncomeExpense.java
 *
 * Created on Oct 10, 2013, 1:21:52 PM
 */
package GUI;

import Business.IncomeExpense;
import DataAccess.CustomerDBHandler;
import DataAccess.EmployeeDBHandler;
import DataAccess.IncomeExpenseDBHandler;
import Model.CustomerListModel;
import Model.EmployeeListModel;
import alecta.gms.pkg1.pkg0.AlectaGMS;

/**
 *
 * @author Chathuranga
 */
public class AddIncomeExpense extends javax.swing.JDialog {
    private int ID;
    /** Creates new form AddIncomeExpense */
    public AddIncomeExpense(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbxCustomer.setModel(new CustomerListModel(new CustomerDBHandler().getCustomers()));
        cmbxResposible.setModel(new EmployeeListModel(new EmployeeDBHandler().getEmployees()));
    }
    
     public AddIncomeExpense(java.awt.Frame parent, boolean modal,int id) {
        super(parent, modal);
        initComponents();
        cmbxCustomer.setModel(new CustomerListModel(new CustomerDBHandler().getCustomers()));
        cmbxResposible.setModel(new EmployeeListModel(new EmployeeDBHandler().getEmployees()));
        ID=id;
        setTitle("Edit Income/Expense");
        IncomeExpense ie=new IncomeExpenseDBHandler().getIncome_ExpenseRecord(id);
        if(ie.getType().equals("Income"))
            rdobtnIncome.setSelected(true);
        if(ie.getType().equals("Expense"))
            rdobtnExpense.setSelected(true);
        txtfldVal.setText(ie.getValue()+"");
        cmbxCustomer.setSelectedItem(ie.getCustomer());
        cmbxResposible.setSelectedItem(ie.getReferenceId()+"");
        txtareaDescription.setText(ie.getDescription());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdobtnIncome = new javax.swing.JRadioButton();
        rdobtnExpense = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtfldVal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbxCustomer = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbxResposible = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDescription = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Income/Expense");

        jLabel1.setText("Type");

        btngrpType.add(rdobtnIncome);
        rdobtnIncome.setSelected(true);
        rdobtnIncome.setText("Income");

        btngrpType.add(rdobtnExpense);
        rdobtnExpense.setText("Expense");

        jLabel2.setText("Value");
        jLabel2.setToolTipText("");

        jLabel3.setText("Customer");
        jLabel3.setToolTipText("");

        cmbxCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Resposible Empyee");

        cmbxResposible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Description");

        txtareaDescription.setColumns(20);
        txtareaDescription.setRows(5);
        jScrollPane1.setViewportView(txtareaDescription);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbxResposible, 0, 204, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdobtnIncome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(rdobtnExpense))
                            .addComponent(txtfldVal, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(cmbxCustomer, 0, 204, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbxResposible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtfldVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(cmbxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(72, 72, 72))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdobtnIncome)
                                .addComponent(rdobtnExpense)
                                .addComponent(jLabel1))
                            .addGap(203, 203, 203))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(btnOK)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-559)/2, (screenSize.height-538)/2, 559, 538);
    }// </editor-fold>//GEN-END:initComponents

private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
    IncomeExpense IE = new IncomeExpense();
    IE.setValue(Double.parseDouble(txtfldVal.getText()));
    IE.setDescription(txtareaDescription.getText());
    IE.setCustomer(cmbxCustomer.getSelectedItem().toString());
    IE.setResponsible(Integer.parseInt(cmbxResposible.getSelectedItem().toString()));
    if(rdobtnIncome.isSelected())
        IE.setType("Income");
    if(rdobtnExpense.isSelected())
        IE.setType("Expense");
    if(this.getTitle().equals("Add Income/Expense"))
        new IncomeExpenseDBHandler().addIncome_Expense(IE);
    if(this.getTitle().equals("Edit Income/Expense")){
        IE.setReferenceId(ID);
        new IncomeExpenseDBHandler().replaceIncomeExpense(IE);}
    Main_Window win = (Main_Window)AlectaGMS.getUser().getParent();
    win.refreshDoubleEntryTable();
    dispose();
}//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddIncomeExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddIncomeExpense dialog = new AddIncomeExpense(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup btngrpType;
    private javax.swing.JComboBox cmbxCustomer;
    private javax.swing.JComboBox cmbxResposible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdobtnExpense;
    private javax.swing.JRadioButton rdobtnIncome;
    private javax.swing.JTextArea txtareaDescription;
    private javax.swing.JTextField txtfldVal;
    // End of variables declaration//GEN-END:variables
}
