/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddOrder.java
 *
 * Created on Oct 7, 2013, 8:47:14 PM
 */
package GUI;

import Business.Customer;
import Business.Order;
import DataAccess.CustomerDBHandler;
import DataAccess.GarmentItemDBHandler;
import DataAccess.OrderDBHandler;
import Model.CustomerListModel;
import Model.GarmentItemListModel;
import alecta.gms.pkg1.pkg0.AlectaGMS;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Chathuranga
 */
public class AddOrder extends javax.swing.JDialog {
    
    private ArrayList entityList;  
    private JComboBox rootEntityComboBox;  
    private ComboBoxModel comboBoxModel;
    int order_ref;
   // private EventBus eventBus;  

    /** Creates new form AddOrder */
    public AddOrder(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbxCustomer.setModel(new CustomerListModel(new CustomerDBHandler().getCustomers()));
        cmbxItemCode.setModel(new GarmentItemListModel(new GarmentItemDBHandler().getGarmentItems()));
        
    }
    
    public AddOrder(java.awt.Frame parent, boolean modal, Order order) {
        super(parent, modal);
        initComponents();
        this.setTitle("Edit Order");
        cmbxCustomer.setModel(new CustomerListModel(new CustomerDBHandler().getCustomers()));
        cmbxCustomer.setSelectedItem(order.getCustomer());
        cmbxItemCode.setModel(new GarmentItemListModel(new GarmentItemDBHandler().getGarmentItems()));
        cmbxItemCode.setSelectedItem(order.getGamentItemCode()+"");
        spnrQty.setValue(order.getQuantity());
        dtpckrDueDate.setDate(order.getDeadLine());
        cmbxStatus.setSelectedItem(order.getStatus());
        order_ref=order.getOrderReference();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpCustomer = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbxItemCode = new javax.swing.JComboBox();
        rdobtnList = new javax.swing.JRadioButton();
        rdobtnNew = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        spnrQty = new javax.swing.JSpinner();
        cmbxCustomer = new javax.swing.JComboBox();
        txtfldName = new javax.swing.JTextField();
        dtpckrDueDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbxStatus = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        txtfldContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Order");

        jLabel1.setText("Customer");

        jLabel2.setText("Garment item code");

        cmbxItemCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btngrpCustomer.add(rdobtnList);
        rdobtnList.setSelected(true);
        rdobtnList.setText("select from list");
        rdobtnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdobtnListActionPerformed(evt);
            }
        });

        btngrpCustomer.add(rdobtnNew);
        rdobtnNew.setText("new customer");
        rdobtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdobtnNewActionPerformed(evt);
            }
        });

        jLabel3.setText("quantity");

        cmbxCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxCustomerActionPerformed(evt);
            }
        });

        txtfldName.setEditable(false);

        jLabel4.setText("Due date");

        jLabel5.setText("Status");

        cmbxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not started", "In process", "Complete" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtfldContact.setEditable(false);

        jLabel6.setText("Name");

        jLabel7.setText("Contact No.");

        jLabel8.setText("Address");

        txtareaAddress.setColumns(20);
        txtareaAddress.setEditable(false);
        txtareaAddress.setRows(5);
        jScrollPane1.setViewportView(txtareaAddress);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnrQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxItemCode, 0, 120, Short.MAX_VALUE)
                            .addComponent(cmbxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtpckrDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(146, 146, 146)
                                    .addComponent(cmbxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdobtnNew)
                                        .addComponent(rdobtnList)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfldContact, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(txtfldName))))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdobtnList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(rdobtnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbxItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnrQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dtpckrDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-467)/2, (screenSize.height-550)/2, 467, 550);
    }// </editor-fold>//GEN-END:initComponents

private void rdobtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdobtnNewActionPerformed
    cmbxCustomer.setEnabled(false);
    txtfldName.setEditable(true);
    txtfldContact.setEditable(true);
    txtareaAddress.setEditable(true);
}//GEN-LAST:event_rdobtnNewActionPerformed

private void rdobtnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdobtnListActionPerformed
    txtfldName.setEditable(false);
    txtfldContact.setEditable(false);
    txtareaAddress.setEditable(false);
    cmbxCustomer.setEnabled(true);
}//GEN-LAST:event_rdobtnListActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Order order = new Order();
    if(rdobtnList.isSelected()){
        order.setCustomer((String)cmbxCustomer.getSelectedItem());
    }
    else if(rdobtnNew.isSelected()){
        order.setCustomer(txtfldName.getText());
        Customer cus=new Customer();
        cus.setCustomerName(txtfldName.getText());
        cus.setContactNo(txtfldContact.getText());
        cus.setAddress(txtareaAddress.getText());
        new CustomerDBHandler().addCustomer(cus);
    }
    java.sql.Date date=new Date(dtpckrDueDate.getDate().getTime());
    order.setDeadLine(date);
    order.setGamentItemCode(Integer.parseInt(cmbxItemCode.getSelectedItem().toString()));
    order.setQuantity(Integer.parseInt(spnrQty.getValue().toString()));
    order.setStatus((String)cmbxStatus.getSelectedItem());
    Calendar calendar = Calendar.getInstance();
    java.util.Date now = calendar.getTime();
    Timestamp currentTimestamp = new Timestamp(now.getTime());
    order.setTimestamp(currentTimestamp);
    if(this.getTitle().equals("Add Order")){
           new OrderDBHandler().addOrder(order);
          }
    else if(this.getTitle().equals("Edit Order")){
        order.setOrderReference(order_ref);
        new OrderDBHandler().replaceRecord(order);}
    Main_Window current=(Main_Window)AlectaGMS.getUser().getParent();
    current.refreshOrderTable();
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void cmbxCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxCustomerActionPerformed
    JComboBox cb = (JComboBox)evt.getSource();
    String item= (String)cb.getSelectedItem();
   /* for (Entity en : entityList) {  
            if (en.getDisplayName().equals(selectedEntityName)) {  
                ERTreeItem rootItem = new ERTreeItem(en);  
                eventBus.publish(new RootEntitySelectedEvent(rootItem));  
            }  
        }  */
    
}//GEN-LAST:event_cmbxCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                AddOrder dialog = new AddOrder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpCustomer;
    private javax.swing.JComboBox cmbxCustomer;
    private javax.swing.JComboBox cmbxItemCode;
    private javax.swing.JComboBox cmbxStatus;
    private org.jdesktop.swingx.JXDatePicker dtpckrDueDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdobtnList;
    private javax.swing.JRadioButton rdobtnNew;
    private javax.swing.JSpinner spnrQty;
    private javax.swing.JTextArea txtareaAddress;
    private javax.swing.JTextField txtfldContact;
    private javax.swing.JTextField txtfldName;
    // End of variables declaration//GEN-END:variables
}
