/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login_GUI.java
 *
 * Created on Sep 17, 2013, 8:45:12 PM
 */
package GUI;

import DataAccess.UserPrevilegesHandler;
import alecta.gms.pkg1.pkg0.Accountant;
import alecta.gms.pkg1.pkg0.Administrator;
import alecta.gms.pkg1.pkg0.AlectaGMS;
import alecta.gms.pkg1.pkg0.DataEntryOperator;
import alecta.gms.pkg1.pkg0.InventoryManager;
import alecta.gms.pkg1.pkg0.OrderHandler;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chathuranga
 */
public class Login_GUI extends javax.swing.JDialog implements GUI_Parent {

    /** Creates new form Login_GUI */
    private String username;
    private String password;
    private boolean ticked;
    public Login_GUI() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Alecta_symbol.png")));
        //txtfldPassword.setVisible(false);
        ticked=false;
        lblError.setVisible(false);
    }
    public Login_GUI(int c) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Alecta_symbol.png")));
        //txtfldPassword.setVisible(false);
        ticked=false;
        lblError.setVisible(true);
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        pwfPassword = new javax.swing.JPasswordField();
        txtfldPassword = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(430, 250));
        setName("frmLogin"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Username");
        jLabel1.setName("lblName"); // NOI18N

        jLabel2.setText("Password");
        jLabel2.setName("lblPassword"); // NOI18N

        jTextField1.setName("txtFldName"); // NOI18N

        jCheckBox1.setText("Unmask");
        jCheckBox1.setName("chkbxUnmask"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.setName("btnLogin"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pwfPassword.setName("pwfPassword"); // NOI18N

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("Incorrect username or password");

        jButton2.setText("Forgot password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtfldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(pwfPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(lblError)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(txtfldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(pwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(lblError)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-474)/2, (screenSize.height-289)/2, 474, 289);
    }// </editor-fold>//GEN-END:initComponents


private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    if(!ticked){
        password=new String(pwfPassword.getPassword());
        pwfPassword.setVisible(false);
        txtfldPassword.setText(password);
        txtfldPassword.setVisible(true);
        txtfldPassword.setLocation(pwfPassword.getLocation());
        ticked=true;
    }
    else{
        password=txtfldPassword.getText();
        txtfldPassword.setVisible(false);
        pwfPassword.setText(password);
        pwfPassword.setVisible(true);
        ticked=false;
    }
}//GEN-LAST:event_jCheckBox1ActionPerformed


private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    if(!ticked)
        password=new String(this.pwfPassword.getPassword());
    if(ticked)
        password=this.txtfldPassword.getText();
    username = this.jTextField1.getText();
    
    System.out.println("password : "+ new UserPrevilegesHandler().getPassword("admin"));
   
    
    Connecting win = new Connecting();
    win.setVisible(true);
        try {
            new Thread().sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String type=new UserPrevilegesHandler().getType(username, password);
        if(type == null){
           // System.exit(0);
            lblError.setVisible(true);
            new Login_GUI(0).setVisible(true);}
        else if(type.equals("abcdefghijklmnopqrstuvwxyz0123456789")){
                
            JOptionPane.showMessageDialog(null, "Database conection lost!", "Connection Lost", JOptionPane.ERROR_MESSAGE);
            
            
        }else{
    if(type.equals("Administrator")){
        //new Main_Window().setVisible(true);
        GUI_Builder builder=new Administrator();
        AlectaGMS.setUser(builder);
        builder.makeMainWindow();
        //setVisible(false);
        //dispose();
    }
    else if(type.equals("Accountant")){
        GUI_Builder builder=new Accountant();
        AlectaGMS.setUser(builder);
        builder.makeMainWindow();
        
        //setVisible(false);
        //dispose();
    }
    else if(type.equals("InventoryManager")){
        GUI_Builder builder=new InventoryManager();
        AlectaGMS.setUser(builder);
        builder.makeMainWindow();
        //dispose();
    }
    else if(type.equals("OrderHandler")){
        GUI_Builder builder = new OrderHandler();
        AlectaGMS.setUser(builder);
        builder.makeMainWindow();
        //dispose();
    }
    else if(type.equals("DataEntry")){
        GUI_Builder builder = new DataEntryOperator();
        AlectaGMS.setUser(builder);
        builder.makeMainWindow();
        //dispose();
    }
  /* else{
        //new Main_Window().setVisible(true);
        GUI_Builder builder=new Administrator();
        AlectaGMS.setUser(builder);
        builder.makeMainWindow();
        //setVisible(false);
        //dispose();
    }*/
        }
    win.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    txtfldPassword.setVisible(false);
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form*/ 
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblError;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txtfldPassword;
    // End of variables declaration//GEN-END:variables
}