/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_Window.java
 *
 * Created on Sep 18, 2013, 11:11:33 PM
 */
package GUI;

import Business.Customer;
import Business.Employee;
import Business.Order;
import DataAccess.CustomerDBHandler;
import DataAccess.EmployeeDBHandler;
import DataAccess.GarmentItemDBHandler;
import DataAccess.IncomeExpenseDBHandler;
import DataAccess.MaterialDBHandler;
import DataAccess.OrderDBHandler;
import DataAccess.SalaryDBHandler;
import Model.CustomerTableModel;
import Model.DoubleEntryTableModel;
import Model.EmployeeTableModel;
import Model.GarmentsTableModel;
import Model.MaterialTableModel;
import Model.OrderTableModel;
import Model.PayRollTableModal;
import alecta.gms.pkg1.pkg0.AlectaGMS;
import alecta.gms.pkg1.pkg0.OrderHandler;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Chathuranga
 */
public class Main_Window extends javax.swing.JFrame implements  GUI_Parent  {

    /** Creates new form Main_Window */
   
    public Main_Window() {
        initComponents();
        //cmbxStatus.setVisible(false);
        tblEmployee.setModel(new EmployeeTableModel());
        tblOrder.setModel(new OrderTableModel());
        tblDEntry.setModel(new DoubleEntryTableModel());
        tblPRoll.setModel(new PayRollTableModal());
        tblMaterial.setModel(new MaterialTableModel());
        tblGarments.setModel(new GarmentsTableModel());
        tblCustomer.setModel(new CustomerTableModel());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Alecta_symbol.png")));
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        //tbpnMainWindow.remove(2);
        lblUser.setText(AlectaGMS.getUser().getTitle());
       
        lyrpnPR.setVisible(false);
        lblExpense_DE.setText(Double.toString(new IncomeExpenseDBHandler().getTotalExpense())+"0");
        lblIncome_DE.setText(Double.toString(new IncomeExpenseDBHandler().getTotalIncome())+"0");
        lblBalance.setText(Double.toString(new IncomeExpenseDBHandler().getTotalIncome()-new IncomeExpenseDBHandler().getTotalExpense())+"0");
        //System.out.println(tblDEntry.getSize().toString());
        lyrpnGarments.setVisible(false);
    }
    public void removeTab(int index){
        tbpnMainWindow.removeTabAt(index);
    }
    public void changeTabName(){
       tbpnMainWindow.setTitleAt(1, "Workbench");
    }
    public void refreshOrderTable(){
        tblOrder.setModel(new OrderTableModel());
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        btnUpdate.setEnabled(false);
        cmbxStatus.setEnabled(false);
        
    }
    public void refreshEmployeeTable(){
        tblEmployee.setModel(new EmployeeTableModel());
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
    }
    public void refreshCustomerTable(){
        tblCustomer.setModel(new CustomerTableModel());
        btnCusEdit.setEnabled(false);
        btnCusDel.setEnabled(false);
    }
    public void refreshDoubleEntryTable(){
        tblDEntry.setModel(new DoubleEntryTableModel());
        lblExpense_DE.setText(Double.toString(new IncomeExpenseDBHandler().getTotalExpense())+"0");
        lblIncome_DE.setText(Double.toString(new IncomeExpenseDBHandler().getTotalIncome())+"0");
        lblBalance.setText(Double.toString(new IncomeExpenseDBHandler().getTotalIncome()-new IncomeExpenseDBHandler().getTotalExpense())+"0");
        btnEdit_DE.setEnabled(false);
        btnDel_DE.setEnabled(false);
        
        
    }
    public void refreshPayRollTable(){
        tblPRoll.setModel(new PayRollTableModal());
        btnDel_PR.setEnabled(false);
    }
    public void refreshGarmentsTable(){
        tblGarments.setModel(new GarmentsTableModel());
        btnDelete_GM.setEnabled(false);
        btnEdit_GM.setEnabled(false);
        btnUpdateQty_GM.setEnabled(false);
        btnUpdateInstock_GM.setEnabled(false);
    }
    public void refreshMaterialTable(){
        tblMaterial.setModel(new MaterialTableModel());
        btnEdit_MA.setEnabled(false);
    btnDelete_MA.setEnabled(false);
    btnUpdate_MA.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpThemes = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tbpnMainWindow = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        btnCusEdit = new javax.swing.JButton();
        btnCusDel = new javax.swing.JButton();
        btnAttnSht = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        pnlAccountant = new javax.swing.JPanel();
        lyrpnPR = new javax.swing.JLayeredPane();
        btnDEntry_PR = new javax.swing.JButton();
        btnPRol_PR = new javax.swing.JButton();
        btnDel_PR = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPRoll = new javax.swing.JTable();
        btnSCalPR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lyrpnlDEntry = new javax.swing.JLayeredPane();
        btnDEntry_DE = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDEntry = new javax.swing.JTable();
        btnPRoll_DE = new javax.swing.JButton();
        btnAdd_DE = new javax.swing.JButton();
        btnEdit_DE = new javax.swing.JButton();
        btnDel_DE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblIncome_DE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblExpense_DE = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlInventry = new javax.swing.JPanel();
        lyrpnMat = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnMaterial_MA = new javax.swing.JButton();
        btnAdd_MA = new javax.swing.JButton();
        btnEdit_MA = new javax.swing.JButton();
        btnDelete_MA = new javax.swing.JButton();
        btnUpdate_MA = new javax.swing.JButton();
        btnGarments_MA = new javax.swing.JButton();
        lyrpnGarments = new javax.swing.JLayeredPane();
        btnUpdateInstock_GM = new javax.swing.JButton();
        btnMaterial_GM = new javax.swing.JButton();
        btnAdd_GM = new javax.swing.JButton();
        btnEdit_GM = new javax.swing.JButton();
        btnDelete_GM = new javax.swing.JButton();
        btnGarmets_GM = new javax.swing.JButton();
        btnUpdateQty_GM = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblGarments = new javax.swing.JTable();
        pnlOrder = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        cmbxStatus = new javax.swing.JComboBox();
        pnlEmployee = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        pnlControl = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        lblUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnbrMainWin = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        mnitmViewdb = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALECTA GMS 1.0");
        setIconImage(getIconImage());
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("User:");

        jButton12.setText("About");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton8.setText("Get Started");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Logo_3.png"))); // NOI18N

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel9)
                .addGap(164, 164, 164)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(150, 150, 150))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        tbpnMainWindow.addTab("Home          ", new javax.swing.ImageIcon(getClass().getResource("/Icons/home-icon.png")), pnlHome); // NOI18N

        btnAddUser.setText("Create new user account");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblCustomer);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Customer Details");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Admin Panel");

        jButton9.setText("Add new customer");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnCusEdit.setText("Edit selected");
        btnCusEdit.setEnabled(false);
        btnCusEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusEditActionPerformed(evt);
            }
        });

        btnCusDel.setText("Delete");
        btnCusDel.setEnabled(false);
        btnCusDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusDelActionPerformed(evt);
            }
        });

        btnAttnSht.setText("Attendance Sheet");
        btnAttnSht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttnShtActionPerformed(evt);
            }
        });

        jButton10.setText("Assign Job Roles");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jLabel2))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addGap(60, 60, 60)
                                .addComponent(btnCusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btnCusDel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3))
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAttnSht, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addGap(70, 70, 70))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton9)
                                    .addComponent(btnCusEdit)
                                    .addComponent(btnCusDel))
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(btnAttnSht, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );

        tbpnMainWindow.addTab("Workbench  ", new javax.swing.ImageIcon(getClass().getResource("/Icons/Work-icon.png")), pnlAdmin); // NOI18N

        btnDEntry_PR.setText("<< Double Entry");
        btnDEntry_PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEntry_PRActionPerformed(evt);
            }
        });
        btnDEntry_PR.setBounds(40, 10, 150, 23);
        lyrpnPR.add(btnDEntry_PR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnPRol_PR.setText("Pay Roll >>");
        btnPRol_PR.setEnabled(false);
        btnPRol_PR.setBounds(850, 10, 140, 23);
        lyrpnPR.add(btnPRol_PR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDel_PR.setText("Delete");
        btnDel_PR.setEnabled(false);
        btnDel_PR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel_PRActionPerformed(evt);
            }
        });
        btnDel_PR.setBounds(1070, 180, 140, 23);
        lyrpnPR.add(btnDel_PR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tblPRoll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPRollMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPRoll);

        jScrollPane4.setBounds(40, 60, 950, 380);
        lyrpnPR.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnSCalPR.setText("Calculate Salary");
        btnSCalPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCalPRActionPerformed(evt);
            }
        });
        btnSCalPR.setBounds(1070, 250, 150, 23);
        lyrpnPR.add(btnSCalPR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Pay Roll Table");
        jLabel5.setBounds(470, 0, 90, 14);
        lyrpnPR.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDEntry_DE.setText("<< Double Entry");
        btnDEntry_DE.setEnabled(false);
        btnDEntry_DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEntry_DEActionPerformed(evt);
            }
        });
        btnDEntry_DE.setBounds(60, 60, 150, 23);
        lyrpnlDEntry.add(btnDEntry_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTitle.setText("Double Entry Table");
        lblTitle.setBounds(480, 50, 120, 14);
        lyrpnlDEntry.add(lblTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tblDEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDEntryMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDEntry);

        jScrollPane3.setBounds(70, 110, 950, 350);
        lyrpnlDEntry.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnPRoll_DE.setText("Pay Roll >>");
        btnPRoll_DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPRoll_DEActionPerformed(evt);
            }
        });
        btnPRoll_DE.setBounds(870, 60, 140, 23);
        lyrpnlDEntry.add(btnPRoll_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAdd_DE.setText("Add Income/Expense");
        btnAdd_DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_DEActionPerformed(evt);
            }
        });
        btnAdd_DE.setBounds(1090, 110, 140, 23);
        lyrpnlDEntry.add(btnAdd_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnEdit_DE.setText("Edit");
        btnEdit_DE.setEnabled(false);
        btnEdit_DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit_DEActionPerformed(evt);
            }
        });
        btnEdit_DE.setBounds(1090, 170, 140, 23);
        lyrpnlDEntry.add(btnEdit_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDel_DE.setText("Delete");
        btnDel_DE.setEnabled(false);
        btnDel_DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel_DEActionPerformed(evt);
            }
        });
        btnDel_DE.setBounds(1090, 230, 140, 23);
        lyrpnlDEntry.add(btnDel_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Total income");
        jLabel4.setBounds(1070, 320, 80, 14);
        lyrpnlDEntry.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblIncome_DE.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblIncome_DE.setForeground(new java.awt.Color(0, 255, 0));
        lblIncome_DE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIncome_DE.setText("lblIncome");
        lblIncome_DE.setBounds(1170, 320, 60, 14);
        lyrpnlDEntry.add(lblIncome_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Total expense");
        jLabel6.setBounds(1070, 370, 80, 14);
        lyrpnlDEntry.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblExpense_DE.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblExpense_DE.setForeground(new java.awt.Color(255, 0, 0));
        lblExpense_DE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExpense_DE.setText("lblExpense");
        lblExpense_DE.setBounds(1170, 370, 60, 14);
        lyrpnlDEntry.add(lblExpense_DE, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Balance");
        jLabel7.setBounds(1070, 420, 70, 14);
        lyrpnlDEntry.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBalance.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblBalance.setForeground(new java.awt.Color(0, 0, 255));
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalance.setText("lblBalance");
        lblBalance.setBounds(1170, 420, 60, 14);
        lyrpnlDEntry.add(lblBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Account Summary (Rs.)");
        jLabel8.setBounds(1070, 280, 170, 17);
        lyrpnlDEntry.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlAccountantLayout = new javax.swing.GroupLayout(pnlAccountant);
        pnlAccountant.setLayout(pnlAccountantLayout);
        pnlAccountantLayout.setHorizontalGroup(
            pnlAccountantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountantLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lyrpnPR, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(pnlAccountantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountantLayout.createSequentialGroup()
                    .addContainerGap(43, Short.MAX_VALUE)
                    .addComponent(lyrpnlDEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlAccountantLayout.setVerticalGroup(
            pnlAccountantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountantLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lyrpnPR, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(pnlAccountantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAccountantLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lyrpnlDEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        tbpnMainWindow.addTab("Accounts      ", new javax.swing.ImageIcon(getClass().getResource("/Icons/Cash-icon.png")), pnlAccountant); // NOI18N

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMaterial);

        jScrollPane5.setBounds(40, 90, 1000, 360);
        lyrpnMat.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMaterial_MA.setText("<< Material");
        btnMaterial_MA.setEnabled(false);
        btnMaterial_MA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterial_MAActionPerformed(evt);
            }
        });
        btnMaterial_MA.setBounds(40, 30, 130, 30);
        lyrpnMat.add(btnMaterial_MA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAdd_MA.setText("Add Material");
        btnAdd_MA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_MAActionPerformed(evt);
            }
        });
        btnAdd_MA.setBounds(1120, 90, 140, 30);
        lyrpnMat.add(btnAdd_MA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnEdit_MA.setText("Edit Material");
        btnEdit_MA.setEnabled(false);
        btnEdit_MA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit_MAActionPerformed(evt);
            }
        });
        btnEdit_MA.setBounds(1120, 170, 140, 30);
        lyrpnMat.add(btnEdit_MA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDelete_MA.setText("Delete Material");
        btnDelete_MA.setEnabled(false);
        btnDelete_MA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_MAActionPerformed(evt);
            }
        });
        btnDelete_MA.setBounds(1120, 250, 140, 30);
        lyrpnMat.add(btnDelete_MA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnUpdate_MA.setText("Update Quantity");
        btnUpdate_MA.setEnabled(false);
        btnUpdate_MA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_MAActionPerformed(evt);
            }
        });
        btnUpdate_MA.setBounds(1120, 330, 140, 30);
        lyrpnMat.add(btnUpdate_MA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGarments_MA.setText("Garments >>");
        btnGarments_MA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGarments_MAActionPerformed(evt);
            }
        });
        btnGarments_MA.setBounds(920, 30, 120, 30);
        lyrpnMat.add(btnGarments_MA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnUpdateInstock_GM.setText("Update In-Stock");
        btnUpdateInstock_GM.setEnabled(false);
        btnUpdateInstock_GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInstock_GMActionPerformed(evt);
            }
        });
        btnUpdateInstock_GM.setBounds(1120, 410, 140, 30);
        lyrpnGarments.add(btnUpdateInstock_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnMaterial_GM.setText("<< Material");
        btnMaterial_GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterial_GMActionPerformed(evt);
            }
        });
        btnMaterial_GM.setBounds(40, 30, 130, 30);
        lyrpnGarments.add(btnMaterial_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAdd_GM.setText("Add Garment Item");
        btnAdd_GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_GMActionPerformed(evt);
            }
        });
        btnAdd_GM.setBounds(1120, 90, 140, 30);
        lyrpnGarments.add(btnAdd_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnEdit_GM.setText("Edit Garment Item");
        btnEdit_GM.setEnabled(false);
        btnEdit_GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit_GMActionPerformed(evt);
            }
        });
        btnEdit_GM.setBounds(1120, 170, 140, 30);
        lyrpnGarments.add(btnEdit_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnDelete_GM.setText("Delete Garment Item");
        btnDelete_GM.setEnabled(false);
        btnDelete_GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_GMActionPerformed(evt);
            }
        });
        btnDelete_GM.setBounds(1120, 250, 140, 30);
        lyrpnGarments.add(btnDelete_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGarmets_GM.setText("Garments >>");
        btnGarmets_GM.setEnabled(false);
        btnGarmets_GM.setBounds(920, 30, 120, 30);
        lyrpnGarments.add(btnGarmets_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnUpdateQty_GM.setText("Update Quantity");
        btnUpdateQty_GM.setEnabled(false);
        btnUpdateQty_GM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateQty_GMActionPerformed(evt);
            }
        });
        btnUpdateQty_GM.setBounds(1120, 330, 140, 30);
        lyrpnGarments.add(btnUpdateQty_GM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tblGarments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGarments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGarmentsMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblGarments);

        jScrollPane6.setBounds(40, 90, 1000, 360);
        lyrpnGarments.add(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlInventryLayout = new javax.swing.GroupLayout(pnlInventry);
        pnlInventry.setLayout(pnlInventryLayout);
        pnlInventryLayout.setHorizontalGroup(
            pnlInventryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lyrpnMat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
            .addGroup(pnlInventryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventryLayout.createSequentialGroup()
                    .addComponent(lyrpnGarments, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlInventryLayout.setVerticalGroup(
            pnlInventryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lyrpnMat, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addGroup(pnlInventryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlInventryLayout.createSequentialGroup()
                    .addComponent(lyrpnGarments, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        tbpnMainWindow.addTab("Inventory       ", new javax.swing.ImageIcon(getClass().getResource("/Icons/box-icon.png")), pnlInventry); // NOI18N

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        jButton13.setText("Add order");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit order");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete order");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update status");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton17.setText("Refresh");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        cmbxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not started", "In progress", "Completed" }));
        cmbxStatus.setEnabled(false);

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13)
                        .addComponent(btnEdit)
                        .addComponent(btnDelete))
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(jButton17))
                        .addGap(4, 4, 4)
                        .addComponent(cmbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpnMainWindow.addTab("Order           ", new javax.swing.ImageIcon(getClass().getResource("/Icons/order-icon.png")), pnlOrder); // NOI18N

        jButton5.setText("Add Employee");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Edit Employee");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Delete Employee");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        javax.swing.GroupLayout pnlEmployeeLayout = new javax.swing.GroupLayout(pnlEmployee);
        pnlEmployee.setLayout(pnlEmployeeLayout);
        pnlEmployeeLayout.setHorizontalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEmployeeLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlEmployeeLayout.setVerticalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbpnMainWindow.addTab("Employees     ", new javax.swing.ImageIcon(getClass().getResource("/Icons/user-icon.png")), pnlEmployee); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Under Construction");

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(554, 554, 554))
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel10)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        tbpnMainWindow.addTab("Control Panel  ", new javax.swing.ImageIcon(getClass().getResource("/Icons/controlpanel-icon.png")), pnlControl); // NOI18N

        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        lblUser.setText("k");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock-icon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LogOff-icon.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        mnbrMainWin.setText("Options");

        jMenuItem3.setText("Configuration Manager");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnbrMainWin.add(jMenuItem3);

        jMenuBar1.add(mnbrMainWin);

        jMenu2.setText("View");

        jMenu4.setText("Themes");

        btngrpThemes.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("HiFi (Default)");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);

        btngrpThemes.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Acryl");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem2);

        btngrpThemes.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("Metal");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem3);

        btngrpThemes.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("Nimbus");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem4);

        jMenu2.add(jMenu4);

        mnitmViewdb.setText("View database");
        mnitmViewdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmViewdbActionPerformed(evt);
            }
        });
        jMenu2.add(mnitmViewdb);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("User");

        jMenuItem2.setText("Log out");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Change Password");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Tools");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbpnMainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 1312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addComponent(jButton4)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUser)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tbpnMainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnitmViewdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmViewdbActionPerformed
    setVisible(false);
}//GEN-LAST:event_mnitmViewdbActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Login_GUI login=new Login_GUI();
    login.setVisible(true);
    login.setLocation(450, 250);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      /* try 
        {
          //UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
            UIManager.setLookAndFeel(new GraphiteLookAndFeel());
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        }*/
         
      AddEmployee addEmployee=new AddEmployee(this, true);
      addEmployee.setVisible(true);
}//GEN-LAST:event_jButton5ActionPerformed

private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed

   // TODO add your handling code here:
     try 
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
            //SwingUtilities.updateComponentTreeUI(this);
            dispose();
            AlectaGMS.getUser().makeMainWindow();
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        }
}//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed

    try 
        {
            UIManager.setLookAndFeel(new MetalLookAndFeel());
            dispose();
            AlectaGMS.getUser().makeMainWindow();
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        }
}//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
    try 
        {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            dispose();
            AlectaGMS.getUser().makeMainWindow();
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        }
}//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
    try 
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            dispose();
            AlectaGMS.getUser().makeMainWindow();
        } 
        catch (Exception e) 
        {
          e.printStackTrace();
        }
}//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    //tbpnMainWindow.remove(0);
   // pnlAdmin.setLayout();
}//GEN-LAST:event_formWindowActivated

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Login_GUI login=new Login_GUI();
    login.setVisible(true);
    login.setLocation(450, 250);
    this.dispose();
}//GEN-LAST:event_jButton4ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    Configuration_Manager config = new Configuration_Manager();
    config.setVisible(true);
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    About aboutWindow=new About(this, true);
    aboutWindow.setVisible(true);
    
}//GEN-LAST:event_jButton12ActionPerformed

private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    AddOrder addWindow = new AddOrder(this, true);
    addWindow.setVisible(true);
}//GEN-LAST:event_jButton13ActionPerformed

private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
    tblOrder.setModel(new OrderTableModel());
}//GEN-LAST:event_jButton17ActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    
    new OrderDBHandler().deleteOrder(Integer.parseInt(tblOrder.getModel().getValueAt(tblOrder.getSelectedRow(), 0).toString()));
    refreshOrderTable();
}//GEN-LAST:event_btnDeleteActionPerformed

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    Order order=new Order();
    order.setOrderReference(Integer.parseInt(tblOrder.getValueAt(tblOrder.getSelectedRow(),0).toString()));
    order.setGamentItemCode(Integer.parseInt(tblOrder.getValueAt(tblOrder.getSelectedRow(),1).toString()));
    order.setCustomer(tblOrder.getValueAt(tblOrder.getSelectedRow(),2).toString());
    order.setQuantity(Integer.parseInt(tblOrder.getValueAt(tblOrder.getSelectedRow(),3).toString()));
    
    String date=tblOrder.getValueAt(tblOrder.getSelectedRow(),4).toString();
    System.out.println(date);
    String[] d = date.split("-");
    System.out.println(d[0]+" "+d[1]+" "+d[2]);
    order.setDeadLine(new Date(Integer.parseInt(d[0])-1900,Integer.parseInt(d[1])-1,Integer.parseInt(d[2])));
    
    order.setStatus(tblOrder.getValueAt(tblOrder.getSelectedRow(),5).toString());
    
    AddOrder win = new AddOrder(this, true,order);
    win.setTitle("Edit Order");
    
    win.setVisible(true);
    refreshOrderTable();
    
}//GEN-LAST:event_btnEditActionPerformed

private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    btnUpdate.setEnabled(false);
    cmbxStatus.setEnabled(false);
    btnEdit.setEnabled(false);
    new OrderDBHandler().updateOrder("Status", cmbxStatus.getSelectedItem().toString(), Integer.parseInt(tblOrder.getModel().getValueAt(tblOrder.getSelectedRow(), 0).toString()));
    refreshOrderTable();
}//GEN-LAST:event_btnUpdateActionPerformed

private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
    btnUpdate.setEnabled(true);
    cmbxStatus.setEnabled(true);
    btnEdit.setEnabled(true);
    btnDelete.setEnabled(true);
}//GEN-LAST:event_tblOrderMouseClicked

private void btnPRoll_DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPRoll_DEActionPerformed
    lyrpnlDEntry.setVisible(false);
    lyrpnPR.setVisible(true);
}//GEN-LAST:event_btnPRoll_DEActionPerformed

private void btnDEntry_DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEntry_DEActionPerformed
    btnDEntry_DE.setEnabled(false);
    btnPRoll_DE.setEnabled(true);
    tblPRoll.setVisible(false);
    tblDEntry.setVisible(true);
    lblTitle.setText("Double Entry Table");
}//GEN-LAST:event_btnDEntry_DEActionPerformed

private void btnGarments_MAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGarments_MAActionPerformed
    lyrpnMat.setVisible(false);
    lyrpnGarments.setVisible(true);
}//GEN-LAST:event_btnGarments_MAActionPerformed

private void btnMaterial_MAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterial_MAActionPerformed
    btnMaterial_MA.setEnabled(false);
    btnGarments_MA.setEnabled(true);
    btnAdd_MA.setVisible(true);
    btnEdit_MA.setVisible(true);
    btnDelete_MA.setVisible(true);
}//GEN-LAST:event_btnMaterial_MAActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    AddCustomer win= new AddCustomer(this, true);
    win.setVisible(true);
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    new EmployeeDBHandler().deleteEmployee(Integer.parseInt(tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 0).toString()));
    refreshEmployeeTable();
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Employee emp = new EmployeeDBHandler().getEmployee(Integer.parseInt(tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 0).toString()));
    AddEmployee win=new AddEmployee(this, true,emp);
    win.setTitle("Edit Employee");
    win.setVisible(true);
}//GEN-LAST:event_jButton6ActionPerformed

private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
    jButton6.setEnabled(true);
    jButton7.setEnabled(true);
}//GEN-LAST:event_tblEmployeeMouseClicked

private void btnCusDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusDelActionPerformed
    new CustomerDBHandler().deleteCustomer(tblCustomer.getValueAt(tblCustomer.getSelectedRow(), 0).toString());  //0->1
    refreshCustomerTable();
}//GEN-LAST:event_btnCusDelActionPerformed

private void btnCusEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusEditActionPerformed
    Customer cus=new Customer();
    cus.setCustomerName(tblCustomer.getValueAt(tblCustomer.getSelectedRow(), 0).toString());
    cus.setContactNo(tblCustomer.getValueAt(tblCustomer.getSelectedRow(), 1).toString());
    cus.setAddress(tblCustomer.getValueAt(tblCustomer.getSelectedRow(), 2).toString());
    AddCustomer win=new AddCustomer(this, true, cus);
    win.setTitle("Edit Customer");
    win.setVisible(true);
}//GEN-LAST:event_btnCusEditActionPerformed

private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
    btnCusEdit.setEnabled(true);
    btnCusDel.setEnabled(true);
}//GEN-LAST:event_tblCustomerMouseClicked

private void btnDEntry_PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEntry_PRActionPerformed
    lyrpnPR.setVisible(false);
    lyrpnlDEntry.setVisible(true);
}//GEN-LAST:event_btnDEntry_PRActionPerformed

private void btnDel_DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel_DEActionPerformed
    new IncomeExpenseDBHandler().deleteRecord(Integer.parseInt(tblDEntry.getValueAt(tblDEntry.getSelectedRow(), 0).toString()));
    refreshDoubleEntryTable();
}//GEN-LAST:event_btnDel_DEActionPerformed

private void btnAdd_DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_DEActionPerformed
    AddIncomeExpense win=new AddIncomeExpense(this, false);
    win.setVisible(true);
}//GEN-LAST:event_btnAdd_DEActionPerformed

private void tblDEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDEntryMouseClicked
    btnEdit_DE.setEnabled(true);
    btnDEntry_DE.setEnabled(true);
    btnDel_DE.setEnabled(true);
}//GEN-LAST:event_tblDEntryMouseClicked

private void btnAttnShtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttnShtActionPerformed
    AttendanceSheet win = new AttendanceSheet();
    win.setVisible(true);
}//GEN-LAST:event_btnAttnShtActionPerformed

private void btnSCalPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCalPRActionPerformed
    SalaryCal_Window win= new SalaryCal_Window(this, true);
    win.setVisible(true);
}//GEN-LAST:event_btnSCalPRActionPerformed

private void btnEdit_MAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit_MAActionPerformed
    int matID=Integer.parseInt(tblMaterial.getValueAt(tblMaterial.getSelectedRow(), 0).toString());
    AddMaterial win= new AddMaterial(this, true,new MaterialDBHandler().getMaterial(matID));
    win.setVisible(true);
}//GEN-LAST:event_btnEdit_MAActionPerformed

private void btnMaterial_GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterial_GMActionPerformed
    lyrpnGarments.setVisible(false);
    lyrpnMat.setVisible(true);
}//GEN-LAST:event_btnMaterial_GMActionPerformed

private void tblMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialMouseClicked
    btnEdit_MA.setEnabled(true);
    btnDelete_MA.setEnabled(true);
    btnUpdate_MA.setEnabled(true);
    
}//GEN-LAST:event_tblMaterialMouseClicked

private void btnAdd_MAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_MAActionPerformed
    AddMaterial win = new AddMaterial(this, true);
    win.setVisible(true);
    refreshMaterialTable();
}//GEN-LAST:event_btnAdd_MAActionPerformed

private void btnDelete_MAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_MAActionPerformed
    new MaterialDBHandler().deleteMaterial(Integer.parseInt(tblMaterial.getValueAt(tblMaterial.getSelectedRow(), 0).toString()));
    refreshMaterialTable();
}//GEN-LAST:event_btnDelete_MAActionPerformed

private void btnUpdate_MAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_MAActionPerformed
    int matID=Integer.parseInt(tblMaterial.getValueAt(tblMaterial.getSelectedRow(), 0).toString());
    UpdateQuantity win=new UpdateQuantity(this, true,matID);
    win.setVisible(true);
}//GEN-LAST:event_btnUpdate_MAActionPerformed

private void btnUpdateQty_GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateQty_GMActionPerformed
    int ID=Integer.parseInt(tblGarments.getValueAt(tblGarments.getSelectedRow(), 0).toString());
    UpdateQuantity win=new UpdateQuantity(this, true,ID);
    win.setTitle("Update Garment Quantity");
    win.setVisible(true);
}//GEN-LAST:event_btnUpdateQty_GMActionPerformed

private void btnUpdateInstock_GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInstock_GMActionPerformed
    int ID=Integer.parseInt(tblGarments.getValueAt(tblGarments.getSelectedRow(), 0).toString());
    UpdateQuantity win=new UpdateQuantity(this, true,ID);
    win.setTitle("Update In-Stock");
    win.setVisible(true);
}//GEN-LAST:event_btnUpdateInstock_GMActionPerformed

private void tblGarmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGarmentsMouseClicked
    btnDelete_GM.setEnabled(true);
        btnEdit_GM.setEnabled(true);
        btnUpdateQty_GM.setEnabled(true);
        btnUpdateInstock_GM.setEnabled(true);
}//GEN-LAST:event_tblGarmentsMouseClicked

private void btnAdd_GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_GMActionPerformed
    AddGarmentItem win = new AddGarmentItem(this, true);
    win.setVisible(true);
            
}//GEN-LAST:event_btnAdd_GMActionPerformed

private void btnEdit_GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit_GMActionPerformed
    int id=Integer.parseInt(tblGarments.getValueAt(tblGarments.getSelectedRow(), 0).toString());
    AddGarmentItem win= new AddGarmentItem(this, true, id);
    win.setVisible(true);
}//GEN-LAST:event_btnEdit_GMActionPerformed

private void btnDelete_GMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_GMActionPerformed
     int id=Integer.parseInt(tblGarments.getValueAt(tblGarments.getSelectedRow(), 0).toString());
     new GarmentItemDBHandler().deleteGarmentItem(id);
     refreshGarmentsTable();
}//GEN-LAST:event_btnDelete_GMActionPerformed

private void btnEdit_DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit_DEActionPerformed
    int id=Integer.parseInt(tblDEntry.getValueAt(tblDEntry.getSelectedRow(), 0).toString());
    AddIncomeExpense win = new AddIncomeExpense(this, true, id);
    win.setVisible(true);
}//GEN-LAST:event_btnEdit_DEActionPerformed

private void btnDel_PRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel_PRActionPerformed
    new SalaryDBHandler().deleteAttendanceRecord(Integer.parseInt(tblPRoll.getValueAt(tblPRoll.getSelectedRow(), 0).toString()));
    refreshPayRollTable();
}//GEN-LAST:event_btnDel_PRActionPerformed

private void tblPRollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPRollMouseClicked
    btnDel_PR.setEnabled(true);
}//GEN-LAST:event_tblPRollMouseClicked

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            Desktop.getDesktop().open(new File("AlectaGMS User Guide.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton8ActionPerformed

private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
    CreateNewAccount win = new CreateNewAccount(this, true);
    win.setVisible(true);
}//GEN-LAST:event_btnAddUserActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    AssignJobs win=new AssignJobs(this, true);
    win.setVisible(true);
}//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main_Window().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAdd_DE;
    private javax.swing.JButton btnAdd_GM;
    private javax.swing.JButton btnAdd_MA;
    private javax.swing.JButton btnAttnSht;
    private javax.swing.JButton btnCusDel;
    private javax.swing.JButton btnCusEdit;
    private javax.swing.JButton btnDEntry_DE;
    private javax.swing.JButton btnDEntry_PR;
    private javax.swing.JButton btnDel_DE;
    private javax.swing.JButton btnDel_PR;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete_GM;
    private javax.swing.JButton btnDelete_MA;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEdit_DE;
    private javax.swing.JButton btnEdit_GM;
    private javax.swing.JButton btnEdit_MA;
    private javax.swing.JButton btnGarments_MA;
    private javax.swing.JButton btnGarmets_GM;
    private javax.swing.JButton btnMaterial_GM;
    private javax.swing.JButton btnMaterial_MA;
    private javax.swing.JButton btnPRol_PR;
    private javax.swing.JButton btnPRoll_DE;
    private javax.swing.JButton btnSCalPR;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateInstock_GM;
    private javax.swing.JButton btnUpdateQty_GM;
    private javax.swing.JButton btnUpdate_MA;
    private javax.swing.ButtonGroup btngrpThemes;
    private javax.swing.JComboBox cmbxStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblExpense_DE;
    private javax.swing.JLabel lblIncome_DE;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLayeredPane lyrpnGarments;
    private javax.swing.JLayeredPane lyrpnMat;
    private javax.swing.JLayeredPane lyrpnPR;
    private javax.swing.JLayeredPane lyrpnlDEntry;
    private javax.swing.JMenu mnbrMainWin;
    private javax.swing.JMenuItem mnitmViewdb;
    private javax.swing.JPanel pnlAccountant;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlEmployee;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlInventry;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblDEntry;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblGarments;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblPRoll;
    private javax.swing.JTabbedPane tbpnMainWindow;
    // End of variables declaration//GEN-END:variables
}
