/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalaryCal_Window.java
 *
 * Created on Oct 9, 2013, 3:35:35 PM
 */
package GUI;

import Business.Employee;
import Business.SalaryCalculator;
import DataAccess.EmployeeDBHandler;
import DataAccess.SalaryDBHandler;
import Model.EmployeeListModel;
import alecta.gms.pkg1.pkg0.AlectaGMS;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import sun.awt.EmbeddedFrame;

/**
 *
 * @author Chathuranga
 */
public class SalaryCal_Window extends javax.swing.JDialog {

    /** Creates new form SalaryCal_Window */
    public SalaryCal_Window(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Calendar c = Calendar.getInstance();
        c.setTimeInMillis(System.currentTimeMillis());
        txtfldYear.setText(Integer.toString(c.get(Calendar.YEAR)));
        
        txtfldMonth.setText(new SimpleDateFormat("MMM").format(c.getTime()));
        cmbxEmpID.setModel(new EmployeeListModel(new EmployeeDBHandler().getEmployees()));
        
        txtfldMonth.setEditable(false);
        txtfldYear.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSalaryOf = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdobtnAll = new javax.swing.JRadioButton();
        rdobtnEmpID = new javax.swing.JRadioButton();
        cmbxEmpID = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        txtfldYear = new javax.swing.JTextField();
        txtfldMonth = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salary Calculator");

        jLabel1.setText("Salary of");

        btngrpSalaryOf.add(rdobtnAll);
        rdobtnAll.setSelected(true);
        rdobtnAll.setText("All");
        rdobtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdobtnAllActionPerformed(evt);
            }
        });

        btngrpSalaryOf.add(rdobtnEmpID);
        rdobtnEmpID.setText("Employee ID");
        rdobtnEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdobtnEmpIDActionPerformed(evt);
            }
        });

        cmbxEmpID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxEmpID.setEnabled(false);

        jLabel2.setText("Year");

        jLabel3.setText("Month");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdobtnAll)
                    .addComponent(txtfldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdobtnEmpID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbxEmpID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(txtfldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdobtnAll)
                    .addComponent(rdobtnEmpID)
                    .addComponent(cmbxEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtfldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-339)/2, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    SalaryCalculator cal = new SalaryCalculator();
    Calendar c = Calendar.getInstance();
    cal.setMonth(c.get(Calendar.YEAR),c.get(Calendar.MONTH));
    if(rdobtnEmpID.isSelected()){
        Employee emp = new EmployeeDBHandler().getEmployee(Integer.parseInt(cmbxEmpID.getSelectedItem().toString()));
        //System.out.println("Emp Id:"+cmbxEmpID.getSelectedItem().toString() );
        new SalaryDBHandler().enterSalary(cal.getSalaryRecord(emp));
        
    }
    else if(rdobtnAll.isSelected()){
        ArrayList<Employee> emps = new EmployeeDBHandler().getEmployees();
        for(int i=0;i<emps.size();i++){
            Employee emp = new EmployeeDBHandler().getEmployee(emps.get(i).getEmpID());
            new SalaryDBHandler().enterSalary(cal.getSalaryRecord(emp));
        }
    }
    Main_Window win=(Main_Window)AlectaGMS.getUser().getParent();
    win.refreshPayRollTable();
    dispose();
    
        
}//GEN-LAST:event_jButton1ActionPerformed

private void rdobtnEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdobtnEmpIDActionPerformed
    cmbxEmpID.setEnabled(true);
}//GEN-LAST:event_rdobtnEmpIDActionPerformed

private void rdobtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdobtnAllActionPerformed
    cmbxEmpID.setEnabled(false);
}//GEN-LAST:event_rdobtnAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryCal_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryCal_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryCal_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryCal_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                SalaryCal_Window dialog = new SalaryCal_Window(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpSalaryOf;
    private javax.swing.JComboBox cmbxEmpID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton rdobtnAll;
    private javax.swing.JRadioButton rdobtnEmpID;
    private javax.swing.JTextField txtfldMonth;
    private javax.swing.JTextField txtfldYear;
    // End of variables declaration//GEN-END:variables
}
